// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Api.V1.Vuce.ForceSchedulingOrchestrator;
using Italcol.TurboGraneles.Clients.Api.V1.Vuce.Health;
using Italcol.TurboGraneles.Clients.Api.V1.Vuce.ReportSae;
using Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendGateinGeneralCargo;
using Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendInspectionLocationAndTimes;
using Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendStuffedContainers;
using Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendStuffingSchedule;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Api.V1.Vuce
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\vuce
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VuceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The forceSchedulingOrchestrator property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.ForceSchedulingOrchestrator.ForceSchedulingOrchestratorRequestBuilder ForceSchedulingOrchestrator
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.ForceSchedulingOrchestrator.ForceSchedulingOrchestratorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.Health.HealthRequestBuilder Health
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reportSae property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.ReportSae.ReportSaeRequestBuilder ReportSae
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.ReportSae.ReportSaeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendGateinGeneralCargo property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendGateinGeneralCargo.SendGateinGeneralCargoRequestBuilder SendGateinGeneralCargo
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendGateinGeneralCargo.SendGateinGeneralCargoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendInspectionLocationAndTimes property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendInspectionLocationAndTimes.SendInspectionLocationAndTimesRequestBuilder SendInspectionLocationAndTimes
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendInspectionLocationAndTimes.SendInspectionLocationAndTimesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendStuffedContainers property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendStuffedContainers.SendStuffedContainersRequestBuilder SendStuffedContainers
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendStuffedContainers.SendStuffedContainersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendStuffingSchedule property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendStuffingSchedule.SendStuffingScheduleRequestBuilder SendStuffingSchedule
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.SendStuffingSchedule.SendStuffingScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.VuceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VuceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/vuce", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Vuce.VuceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VuceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/vuce", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
