// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\super-financiera\erp-update-currency-rate\{company}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCompanyItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Italcol.TurboGraneles.Clients.api.v1.superFinanciera.erpUpdateCurrencyRate.item.item collection</summary>
        /// <param name="position">Currency type (e.g., 1)</param>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate.Item.Item.WithCurrencyTypeItemRequestBuilder"/></returns>
        public global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate.Item.Item.WithCurrencyTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("currencyType", position);
                return new global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate.Item.Item.WithCurrencyTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate.Item.WithCompanyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCompanyItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/super-financiera/erp-update-currency-rate/{company}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate.Item.WithCompanyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCompanyItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/super-financiera/erp-update-currency-rate/{company}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
