// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Api.V1.Email.Health;
using Italcol.TurboGraneles.Clients.Api.V1.Email.Send;
using Italcol.TurboGraneles.Clients.Api.V1.Email.Templates;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Api.V1.Email
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\email
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmailRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The health property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Email.Health.HealthRequestBuilder Health
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Email.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The send property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Email.Send.SendRequestBuilder Send
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Email.Send.SendRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The templates property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Email.Templates.TemplatesRequestBuilder Templates
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Email.Templates.TemplatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Email.EmailRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/email", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Email.EmailRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmailRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/email", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
