// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Api.V1.Jobs.Endpoints;
using Italcol.TurboGraneles.Clients.Api.V1.Jobs.Process;
using Italcol.TurboGraneles.Clients.Api.V1.Jobs.Statuses;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Api.V1.Jobs
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\jobs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JobsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The endpoints property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.Endpoints.EndpointsRequestBuilder Endpoints
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.Endpoints.EndpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The process property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.Process.ProcessRequestBuilder Process
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.Process.ProcessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The statuses property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.Statuses.StatusesRequestBuilder Statuses
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.Statuses.StatusesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.JobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JobsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/jobs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Jobs.JobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JobsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/jobs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
