// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpSetCurrencyRate;
using Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate;
using Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.GetTodayTrm;
using Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.Health;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\super-financiera
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuperFinancieraRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The erpSetCurrencyRate property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpSetCurrencyRate.ErpSetCurrencyRateRequestBuilder ErpSetCurrencyRate
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpSetCurrencyRate.ErpSetCurrencyRateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The erpUpdateCurrencyRate property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate.ErpUpdateCurrencyRateRequestBuilder ErpUpdateCurrencyRate
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.ErpUpdateCurrencyRate.ErpUpdateCurrencyRateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getTodayTrm property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.GetTodayTrm.GetTodayTrmRequestBuilder GetTodayTrm
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.GetTodayTrm.GetTodayTrmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.Health.HealthRequestBuilder Health
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.SuperFinancieraRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuperFinancieraRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/super-financiera", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.SuperFinanciera.SuperFinancieraRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuperFinancieraRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/super-financiera", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
