// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    /// <summary>Type of cargo</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AppointmentValidationBody_classCargo
    {
        [EnumMember(Value = "Import")]
        #pragma warning disable CS1591
        Import,
        #pragma warning restore CS1591
        [EnumMember(Value = "Export")]
        #pragma warning disable CS1591
        Export,
        #pragma warning restore CS1591
        [EnumMember(Value = "Mixed")]
        #pragma warning disable CS1591
        Mixed,
        #pragma warning restore CS1591
    }
}
