// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AppointmentValidationBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Appointment date</summary>
        public DateTimeOffset? AppointmentDate { get; set; }
        /// <summary>Type of cargo</summary>
        public global::Italcol.TurboGraneles.Clients.Models.AppointmentValidationBody_classCargo? ClassCargo { get; set; }
        /// <summary>Driver identification</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Driver { get; set; }
#nullable restore
#else
        public string Driver { get; set; }
#endif
        /// <summary>Entry Id (IdManifest)</summary>
        public double? ManifestNbr { get; set; }
        /// <summary>Truck license plate</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Truck { get; set; }
#nullable restore
#else
        public string Truck { get; set; }
#endif
        /// <summary>Truck company ID (with verification digit)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TruckCompanyId { get; set; }
#nullable restore
#else
        public string TruckCompanyId { get; set; }
#endif
        /// <summary>Validation type identifier</summary>
        public global::Italcol.TurboGraneles.Clients.Models.ValidationType? ValidationType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.AppointmentValidationBody"/> and sets the default values.
        /// </summary>
        public AppointmentValidationBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.AppointmentValidationBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.AppointmentValidationBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.AppointmentValidationBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "appointmentDate", n => { AppointmentDate = n.GetDateTimeOffsetValue(); } },
                { "classCargo", n => { ClassCargo = n.GetEnumValue<global::Italcol.TurboGraneles.Clients.Models.AppointmentValidationBody_classCargo>(); } },
                { "driver", n => { Driver = n.GetStringValue(); } },
                { "manifestNbr", n => { ManifestNbr = n.GetDoubleValue(); } },
                { "truck", n => { Truck = n.GetStringValue(); } },
                { "truckCompanyId", n => { TruckCompanyId = n.GetStringValue(); } },
                { "validationType", n => { ValidationType = n.GetEnumValue<global::Italcol.TurboGraneles.Clients.Models.ValidationType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("appointmentDate", AppointmentDate);
            writer.WriteEnumValue<global::Italcol.TurboGraneles.Clients.Models.AppointmentValidationBody_classCargo>("classCargo", ClassCargo);
            writer.WriteStringValue("driver", Driver);
            writer.WriteDoubleValue("manifestNbr", ManifestNbr);
            writer.WriteStringValue("truck", Truck);
            writer.WriteStringValue("truckCompanyId", TruckCompanyId);
            writer.WriteEnumValue<global::Italcol.TurboGraneles.Clients.Models.ValidationType>("validationType", ValidationType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
