// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    /// <summary>Proceso asociado al grupo de correos</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateEmailGroupDto_process
    {
        [EnumMember(Value = "AUTH")]
        #pragma warning disable CS1591
        AUTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRM")]
        #pragma warning disable CS1591
        TRM,
        #pragma warning restore CS1591
        [EnumMember(Value = "VUCE")]
        #pragma warning disable CS1591
        VUCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MINTRANSPORTE")]
        #pragma warning disable CS1591
        MINTRANSPORTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DIAN")]
        #pragma warning disable CS1591
        DIAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "MIIT")]
        #pragma warning disable CS1591
        MIIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIIS")]
        #pragma warning disable CS1591
        SIIS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOS")]
        #pragma warning disable CS1591
        TOS,
        #pragma warning restore CS1591
        [EnumMember(Value = "USERS")]
        #pragma warning disable CS1591
        USERS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCESS_CONTROL")]
        #pragma warning disable CS1591
        ACCESS_CONTROL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCANNER")]
        #pragma warning disable CS1591
        SCANNER,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCALEWEIGHT")]
        #pragma warning disable CS1591
        SCALEWEIGHT,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAILGROUPS")]
        #pragma warning disable CS1591
        EMAILGROUPS,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAFETEROS")]
        #pragma warning disable CS1591
        CAFETEROS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ELECTRONIC_INVOICE")]
        #pragma warning disable CS1591
        ELECTRONIC_INVOICE,
        #pragma warning restore CS1591
        [EnumMember(Value = "OAUTH2")]
        #pragma warning disable CS1591
        OAUTH2,
        #pragma warning restore CS1591
    }
}
