// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DinformeDetallesCargarecibidaDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Cargo type</summary>
        public global::Italcol.TurboGraneles.Clients.Models.DinformeDetallesCargarecibidaDto_cargoType? CargoType { get; set; }
        /// <summary>Empty containers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Italcol.TurboGraneles.Clients.Models.ContenedorVacioDto>? ContenedoresVacios { get; set; }
#nullable restore
#else
        public List<global::Italcol.TurboGraneles.Clients.Models.ContenedorVacioDto> ContenedoresVacios { get; set; }
#endif
        /// <summary>Transport line</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Linea { get; set; }
#nullable restore
#else
        public string Linea { get; set; }
#endif
        /// <summary>Vessel name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NombreMotonave { get; set; }
#nullable restore
#else
        public string NombreMotonave { get; set; }
#endif
        /// <summary>Terminal recaladas number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumeroRecaladaTerminal { get; set; }
#nullable restore
#else
        public string NumeroRecaladaTerminal { get; set; }
#endif
        /// <summary>Previous format number</summary>
        public double? NumFormatoAnterior { get; set; }
        /// <summary>Manifest number</summary>
        public double? NumManifiesto { get; set; }
        /// <summary>Destination port reported by the shipping line</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PodReportadoNaviero { get; set; }
#nullable restore
#else
        public string PodReportadoNaviero { get; set; }
#endif
        /// <summary>Received cargo units</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Italcol.TurboGraneles.Clients.Models.UnidadCargaRecibidaDto>? UnidadesCargaRecibida { get; set; }
#nullable restore
#else
        public List<global::Italcol.TurboGraneles.Clients.Models.UnidadCargaRecibidaDto> UnidadesCargaRecibida { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.DinformeDetallesCargarecibidaDto"/> and sets the default values.
        /// </summary>
        public DinformeDetallesCargarecibidaDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.DinformeDetallesCargarecibidaDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.DinformeDetallesCargarecibidaDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.DinformeDetallesCargarecibidaDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cargoType", n => { CargoType = n.GetEnumValue<global::Italcol.TurboGraneles.Clients.Models.DinformeDetallesCargarecibidaDto_cargoType>(); } },
                { "contenedoresVacios", n => { ContenedoresVacios = n.GetCollectionOfObjectValues<global::Italcol.TurboGraneles.Clients.Models.ContenedorVacioDto>(global::Italcol.TurboGraneles.Clients.Models.ContenedorVacioDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "linea", n => { Linea = n.GetStringValue(); } },
                { "nombreMotonave", n => { NombreMotonave = n.GetStringValue(); } },
                { "numFormatoAnterior", n => { NumFormatoAnterior = n.GetDoubleValue(); } },
                { "numManifiesto", n => { NumManifiesto = n.GetDoubleValue(); } },
                { "numeroRecaladaTerminal", n => { NumeroRecaladaTerminal = n.GetStringValue(); } },
                { "podReportadoNaviero", n => { PodReportadoNaviero = n.GetStringValue(); } },
                { "unidadesCargaRecibida", n => { UnidadesCargaRecibida = n.GetCollectionOfObjectValues<global::Italcol.TurboGraneles.Clients.Models.UnidadCargaRecibidaDto>(global::Italcol.TurboGraneles.Clients.Models.UnidadCargaRecibidaDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Italcol.TurboGraneles.Clients.Models.DinformeDetallesCargarecibidaDto_cargoType>("cargoType", CargoType);
            writer.WriteCollectionOfObjectValues<global::Italcol.TurboGraneles.Clients.Models.ContenedorVacioDto>("contenedoresVacios", ContenedoresVacios);
            writer.WriteStringValue("linea", Linea);
            writer.WriteStringValue("nombreMotonave", NombreMotonave);
            writer.WriteStringValue("numeroRecaladaTerminal", NumeroRecaladaTerminal);
            writer.WriteDoubleValue("numFormatoAnterior", NumFormatoAnterior);
            writer.WriteDoubleValue("numManifiesto", NumManifiesto);
            writer.WriteStringValue("podReportadoNaviero", PodReportadoNaviero);
            writer.WriteCollectionOfObjectValues<global::Italcol.TurboGraneles.Clients.Models.UnidadCargaRecibidaDto>("unidadesCargaRecibida", UnidadesCargaRecibida);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
