// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    /// <summary>Cargo type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DinformeDetallesCargarecibidaDto_cargoType
    {
        [EnumMember(Value = "CC")]
        #pragma warning disable CS1591
        CC,
        #pragma warning restore CS1591
        [EnumMember(Value = "CG")]
        #pragma warning disable CS1591
        CG,
        #pragma warning restore CS1591
        [EnumMember(Value = "CS")]
        #pragma warning disable CS1591
        CS,
        #pragma warning restore CS1591
        [EnumMember(Value = "CR")]
        #pragma warning disable CS1591
        CR,
        #pragma warning restore CS1591
    }
}
