// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetGateInDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Arrival date and time</summary>
        public DateTimeOffset? ArriveDateTime { get; set; }
        /// <summary>Arrival weight in tons</summary>
        public double? ArriveWeight { get; set; }
        /// <summary>Maximum weight permitted</summary>
        public double? MaxWeightPermitted { get; set; }
        /// <summary>Truck plate number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TruckPlate { get; set; }
#nullable restore
#else
        public string TruckPlate { get; set; }
#endif
        /// <summary>Truck transaction identifier</summary>
        public double? TruckTransaction { get; set; }
        /// <summary>Weighing bridge identifier</summary>
        public double? WeighingBridgeId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.GetGateInDto"/> and sets the default values.
        /// </summary>
        public GetGateInDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.GetGateInDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.GetGateInDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.GetGateInDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "arriveDateTime", n => { ArriveDateTime = n.GetDateTimeOffsetValue(); } },
                { "arriveWeight", n => { ArriveWeight = n.GetDoubleValue(); } },
                { "maxWeightPermitted", n => { MaxWeightPermitted = n.GetDoubleValue(); } },
                { "truckPlate", n => { TruckPlate = n.GetStringValue(); } },
                { "truckTransaction", n => { TruckTransaction = n.GetDoubleValue(); } },
                { "weighingBridgeId", n => { WeighingBridgeId = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("arriveDateTime", ArriveDateTime);
            writer.WriteDoubleValue("arriveWeight", ArriveWeight);
            writer.WriteDoubleValue("maxWeightPermitted", MaxWeightPermitted);
            writer.WriteStringValue("truckPlate", TruckPlate);
            writer.WriteDoubleValue("truckTransaction", TruckTransaction);
            writer.WriteDoubleValue("weighingBridgeId", WeighingBridgeId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
