// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetVoyageandVesselDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Estimated Time of Arrival (ETA)</summary>
        public DateTimeOffset? Eta { get; set; }
        /// <summary>Estimated Time of Departure (ETD)</summary>
        public DateTimeOffset? Etd { get; set; }
        /// <summary>Name of the vessel</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VesselName { get; set; }
#nullable restore
#else
        public string VesselName { get; set; }
#endif
        /// <summary>Vessel voyage identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VesselVoyage { get; set; }
#nullable restore
#else
        public string VesselVoyage { get; set; }
#endif
        /// <summary>Voyage identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Voyage { get; set; }
#nullable restore
#else
        public string Voyage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.GetVoyageandVesselDto"/> and sets the default values.
        /// </summary>
        public GetVoyageandVesselDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.GetVoyageandVesselDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.GetVoyageandVesselDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.GetVoyageandVesselDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "eta", n => { Eta = n.GetDateTimeOffsetValue(); } },
                { "etd", n => { Etd = n.GetDateTimeOffsetValue(); } },
                { "vesselName", n => { VesselName = n.GetStringValue(); } },
                { "vesselVoyage", n => { VesselVoyage = n.GetStringValue(); } },
                { "voyage", n => { Voyage = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("eta", Eta);
            writer.WriteDateTimeOffsetValue("etd", Etd);
            writer.WriteStringValue("vesselName", VesselName);
            writer.WriteStringValue("vesselVoyage", VesselVoyage);
            writer.WriteStringValue("voyage", Voyage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
