// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestArimCargoFromTosDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of packages</summary>
        public double? CantidadBultos { get; set; }
        /// <summary>CC: Container cargo, CG: General Cargo, CS: Bulk Cargo, CR: Ro Ro Cargo</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CargoType { get; set; }
#nullable restore
#else
        public string CargoType { get; set; }
#endif
        /// <summary>Destination deposit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DepositoDestino { get; set; }
#nullable restore
#else
        public string DepositoDestino { get; set; }
#endif
        /// <summary>Company requesting the withdrawal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmpresaSolicitaRetiro { get; set; }
#nullable restore
#else
        public string EmpresaSolicitaRetiro { get; set; }
#endif
        /// <summary>Customs status of the cargo</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EstadoAduaneroCarga { get; set; }
#nullable restore
#else
        public string EstadoAduaneroCarga { get; set; }
#endif
        /// <summary>Container number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumeroContenedor { get; set; }
#nullable restore
#else
        public string NumeroContenedor { get; set; }
#endif
        /// <summary>Transport document number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumeroDocumentoTransporte { get; set; }
#nullable restore
#else
        public string NumeroDocumentoTransporte { get; set; }
#endif
        /// <summary>Manifest number</summary>
        public double? NumeroManifiestoCarga { get; set; }
        /// <summary>Visit Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumeroRetiroCarga { get; set; }
#nullable restore
#else
        public string NumeroRetiroCarga { get; set; }
#endif
        /// <summary>Weight of the cargo</summary>
        public double? PesoCarga { get; set; }
        /// <summary>Seal number of the container</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sello1 { get; set; }
#nullable restore
#else
        public string Sello1 { get; set; }
#endif
        /// <summary>Container size</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TamanoContenedor { get; set; }
#nullable restore
#else
        public string TamanoContenedor { get; set; }
#endif
        /// <summary>Type of container</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TipoContenedor { get; set; }
#nullable restore
#else
        public string TipoContenedor { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.RequestArimCargoFromTosDto"/> and sets the default values.
        /// </summary>
        public RequestArimCargoFromTosDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.RequestArimCargoFromTosDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.RequestArimCargoFromTosDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.RequestArimCargoFromTosDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cantidadBultos", n => { CantidadBultos = n.GetDoubleValue(); } },
                { "cargoType", n => { CargoType = n.GetStringValue(); } },
                { "depositoDestino", n => { DepositoDestino = n.GetStringValue(); } },
                { "empresaSolicitaRetiro", n => { EmpresaSolicitaRetiro = n.GetStringValue(); } },
                { "estadoAduaneroCarga", n => { EstadoAduaneroCarga = n.GetStringValue(); } },
                { "numeroContenedor", n => { NumeroContenedor = n.GetStringValue(); } },
                { "numeroDocumentoTransporte", n => { NumeroDocumentoTransporte = n.GetStringValue(); } },
                { "numeroManifiestoCarga", n => { NumeroManifiestoCarga = n.GetDoubleValue(); } },
                { "numeroRetiroCarga", n => { NumeroRetiroCarga = n.GetStringValue(); } },
                { "pesoCarga", n => { PesoCarga = n.GetDoubleValue(); } },
                { "sello1", n => { Sello1 = n.GetStringValue(); } },
                { "tamanoContenedor", n => { TamanoContenedor = n.GetStringValue(); } },
                { "tipoContenedor", n => { TipoContenedor = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("cantidadBultos", CantidadBultos);
            writer.WriteStringValue("cargoType", CargoType);
            writer.WriteStringValue("depositoDestino", DepositoDestino);
            writer.WriteStringValue("empresaSolicitaRetiro", EmpresaSolicitaRetiro);
            writer.WriteStringValue("estadoAduaneroCarga", EstadoAduaneroCarga);
            writer.WriteStringValue("numeroContenedor", NumeroContenedor);
            writer.WriteStringValue("numeroDocumentoTransporte", NumeroDocumentoTransporte);
            writer.WriteDoubleValue("numeroManifiestoCarga", NumeroManifiestoCarga);
            writer.WriteStringValue("numeroRetiroCarga", NumeroRetiroCarga);
            writer.WriteDoubleValue("pesoCarga", PesoCarga);
            writer.WriteStringValue("sello1", Sello1);
            writer.WriteStringValue("tamanoContenedor", TamanoContenedor);
            writer.WriteStringValue("tipoContenedor", TipoContenedor);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
