// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestPayloadDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agenteDeAduanas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgenteDeAduanas { get; set; }
#nullable restore
#else
        public string AgenteDeAduanas { get; set; }
#endif
        /// <summary>The anioCafetero property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnioCafetero { get; set; }
#nullable restore
#else
        public string AnioCafetero { get; set; }
#endif
        /// <summary>The bodega property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bodega { get; set; }
#nullable restore
#else
        public string Bodega { get; set; }
#endif
        /// <summary>The cantidadEstibas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CantidadEstibas { get; set; }
#nullable restore
#else
        public string CantidadEstibas { get; set; }
#endif
        /// <summary>The cantidadSacos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CantidadSacos { get; set; }
#nullable restore
#else
        public string CantidadSacos { get; set; }
#endif
        /// <summary>The clavePais property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClavePais { get; set; }
#nullable restore
#else
        public string ClavePais { get; set; }
#endif
        /// <summary>The codigoExportador property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodigoExportador { get; set; }
#nullable restore
#else
        public string CodigoExportador { get; set; }
#endif
        /// <summary>The empresaTransportadora property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmpresaTransportadora { get; set; }
#nullable restore
#else
        public string EmpresaTransportadora { get; set; }
#endif
        /// <summary>Date in YYYY-MM-DD format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fecha { get; set; }
#nullable restore
#else
        public string Fecha { get; set; }
#endif
        /// <summary>The guiaTransito property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GuiaTransito { get; set; }
#nullable restore
#else
        public string GuiaTransito { get; set; }
#endif
        /// <summary>The idBascula property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdBascula { get; set; }
#nullable restore
#else
        public string IdBascula { get; set; }
#endif
        /// <summary>The kilosBrutosPorCafe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KilosBrutosPorCafe { get; set; }
#nullable restore
#else
        public string KilosBrutosPorCafe { get; set; }
#endif
        /// <summary>The kilosNetosCafe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KilosNetosCafe { get; set; }
#nullable restore
#else
        public string KilosNetosCafe { get; set; }
#endif
        /// <summary>The numeroEntrega property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumeroEntrega { get; set; }
#nullable restore
#else
        public string NumeroEntrega { get; set; }
#endif
        /// <summary>The numeroLote property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumeroLote { get; set; }
#nullable restore
#else
        public string NumeroLote { get; set; }
#endif
        /// <summary>The numeroMaterial property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumeroMaterial { get; set; }
#nullable restore
#else
        public string NumeroMaterial { get; set; }
#endif
        /// <summary>The observaciones property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Observaciones { get; set; }
#nullable restore
#else
        public string Observaciones { get; set; }
#endif
        /// <summary>The opciones1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Opciones1 { get; set; }
#nullable restore
#else
        public string Opciones1 { get; set; }
#endif
        /// <summary>The pesoBrutoCafeSinEstibas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PesoBrutoCafeSinEstibas { get; set; }
#nullable restore
#else
        public string PesoBrutoCafeSinEstibas { get; set; }
#endif
        /// <summary>The pesoEstibas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PesoEstibas { get; set; }
#nullable restore
#else
        public string PesoEstibas { get; set; }
#endif
        /// <summary>The placa property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Placa { get; set; }
#nullable restore
#else
        public string Placa { get; set; }
#endif
        /// <summary>The planillaBodega property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanillaBodega { get; set; }
#nullable restore
#else
        public string PlanillaBodega { get; set; }
#endif
        /// <summary>The procedencia property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Procedencia { get; set; }
#nullable restore
#else
        public string Procedencia { get; set; }
#endif
        /// <summary>The sacosRecibidos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SacosRecibidos { get; set; }
#nullable restore
#else
        public string SacosRecibidos { get; set; }
#endif
        /// <summary>The taraEmpaque property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaraEmpaque { get; set; }
#nullable restore
#else
        public string TaraEmpaque { get; set; }
#endif
        /// <summary>The usuario property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Usuario { get; set; }
#nullable restore
#else
        public string Usuario { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.RequestPayloadDto"/> and sets the default values.
        /// </summary>
        public RequestPayloadDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.RequestPayloadDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.RequestPayloadDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.RequestPayloadDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agenteDeAduanas", n => { AgenteDeAduanas = n.GetStringValue(); } },
                { "anioCafetero", n => { AnioCafetero = n.GetStringValue(); } },
                { "bodega", n => { Bodega = n.GetStringValue(); } },
                { "cantidadEstibas", n => { CantidadEstibas = n.GetStringValue(); } },
                { "cantidadSacos", n => { CantidadSacos = n.GetStringValue(); } },
                { "clavePais", n => { ClavePais = n.GetStringValue(); } },
                { "codigoExportador", n => { CodigoExportador = n.GetStringValue(); } },
                { "empresaTransportadora", n => { EmpresaTransportadora = n.GetStringValue(); } },
                { "fecha", n => { Fecha = n.GetStringValue(); } },
                { "guiaTransito", n => { GuiaTransito = n.GetStringValue(); } },
                { "idBascula", n => { IdBascula = n.GetStringValue(); } },
                { "kilosBrutosPorCafe", n => { KilosBrutosPorCafe = n.GetStringValue(); } },
                { "kilosNetosCafe", n => { KilosNetosCafe = n.GetStringValue(); } },
                { "numeroEntrega", n => { NumeroEntrega = n.GetStringValue(); } },
                { "numeroLote", n => { NumeroLote = n.GetStringValue(); } },
                { "numeroMaterial", n => { NumeroMaterial = n.GetStringValue(); } },
                { "observaciones", n => { Observaciones = n.GetStringValue(); } },
                { "opciones1", n => { Opciones1 = n.GetStringValue(); } },
                { "pesoBrutoCafeSinEstibas", n => { PesoBrutoCafeSinEstibas = n.GetStringValue(); } },
                { "pesoEstibas", n => { PesoEstibas = n.GetStringValue(); } },
                { "placa", n => { Placa = n.GetStringValue(); } },
                { "planillaBodega", n => { PlanillaBodega = n.GetStringValue(); } },
                { "procedencia", n => { Procedencia = n.GetStringValue(); } },
                { "sacosRecibidos", n => { SacosRecibidos = n.GetStringValue(); } },
                { "taraEmpaque", n => { TaraEmpaque = n.GetStringValue(); } },
                { "usuario", n => { Usuario = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("agenteDeAduanas", AgenteDeAduanas);
            writer.WriteStringValue("anioCafetero", AnioCafetero);
            writer.WriteStringValue("bodega", Bodega);
            writer.WriteStringValue("cantidadEstibas", CantidadEstibas);
            writer.WriteStringValue("cantidadSacos", CantidadSacos);
            writer.WriteStringValue("clavePais", ClavePais);
            writer.WriteStringValue("codigoExportador", CodigoExportador);
            writer.WriteStringValue("empresaTransportadora", EmpresaTransportadora);
            writer.WriteStringValue("fecha", Fecha);
            writer.WriteStringValue("guiaTransito", GuiaTransito);
            writer.WriteStringValue("idBascula", IdBascula);
            writer.WriteStringValue("kilosBrutosPorCafe", KilosBrutosPorCafe);
            writer.WriteStringValue("kilosNetosCafe", KilosNetosCafe);
            writer.WriteStringValue("numeroEntrega", NumeroEntrega);
            writer.WriteStringValue("numeroLote", NumeroLote);
            writer.WriteStringValue("numeroMaterial", NumeroMaterial);
            writer.WriteStringValue("observaciones", Observaciones);
            writer.WriteStringValue("opciones1", Opciones1);
            writer.WriteStringValue("pesoBrutoCafeSinEstibas", PesoBrutoCafeSinEstibas);
            writer.WriteStringValue("pesoEstibas", PesoEstibas);
            writer.WriteStringValue("placa", Placa);
            writer.WriteStringValue("planillaBodega", PlanillaBodega);
            writer.WriteStringValue("procedencia", Procedencia);
            writer.WriteStringValue("sacosRecibidos", SacosRecibidos);
            writer.WriteStringValue("taraEmpaque", TaraEmpaque);
            writer.WriteStringValue("usuario", Usuario);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
