// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    /// <summary>Current status of the vessel load</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SendCustomsReleasedCargoStatus
    {
        [EnumMember(Value = "Release")]
        #pragma warning disable CS1591
        Release,
        #pragma warning restore CS1591
        [EnumMember(Value = "Apply")]
        #pragma warning disable CS1591
        Apply,
        #pragma warning restore CS1591
    }
}
