// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SendStuffedContainersBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Consecutive stuffing</summary>
        public double? ConsecutiveStuffing { get; set; }
        /// <summary>Container</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Container { get; set; }
#nullable restore
#else
        public string Container { get; set; }
#endif
        /// <summary>Programming number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgrammingNbr { get; set; }
#nullable restore
#else
        public string ProgrammingNbr { get; set; }
#endif
        /// <summary>Seals</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Seals { get; set; }
#nullable restore
#else
        public string Seals { get; set; }
#endif
        /// <summary>Service numbers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Italcol.TurboGraneles.Clients.Models.ServiceNumber>? ServiceNbrs { get; set; }
#nullable restore
#else
        public List<global::Italcol.TurboGraneles.Clients.Models.ServiceNumber> ServiceNbrs { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.SendStuffedContainersBody"/> and sets the default values.
        /// </summary>
        public SendStuffedContainersBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.SendStuffedContainersBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.SendStuffedContainersBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.SendStuffedContainersBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "consecutiveStuffing", n => { ConsecutiveStuffing = n.GetDoubleValue(); } },
                { "container", n => { Container = n.GetStringValue(); } },
                { "programmingNbr", n => { ProgrammingNbr = n.GetStringValue(); } },
                { "seals", n => { Seals = n.GetStringValue(); } },
                { "serviceNbrs", n => { ServiceNbrs = n.GetCollectionOfObjectValues<global::Italcol.TurboGraneles.Clients.Models.ServiceNumber>(global::Italcol.TurboGraneles.Clients.Models.ServiceNumber.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("consecutiveStuffing", ConsecutiveStuffing);
            writer.WriteStringValue("container", Container);
            writer.WriteStringValue("programmingNbr", ProgrammingNbr);
            writer.WriteStringValue("seals", Seals);
            writer.WriteCollectionOfObjectValues<global::Italcol.TurboGraneles.Clients.Models.ServiceNumber>("serviceNbrs", ServiceNbrs);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
