// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SendReceiptRecordDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>End date and time of the operation</summary>
        public DateTimeOffset? DateTimeEnd { get; set; }
        /// <summary>Transaction identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdTransaction { get; set; }
#nullable restore
#else
        public string IdTransaction { get; set; }
#endif
        /// <summary>Product identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductId { get; set; }
#nullable restore
#else
        public string ProductId { get; set; }
#endif
        /// <summary>Receipt weight in kilograms</summary>
        public double? ReceiptWeight { get; set; }
        /// <summary>Voyage identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Voyage { get; set; }
#nullable restore
#else
        public string Voyage { get; set; }
#endif
        /// <summary>Weighing pit identifier</summary>
        public double? WeighingPit { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.SendReceiptRecordDto"/> and sets the default values.
        /// </summary>
        public SendReceiptRecordDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.SendReceiptRecordDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.SendReceiptRecordDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.SendReceiptRecordDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "DateTimeEnd", n => { DateTimeEnd = n.GetDateTimeOffsetValue(); } },
                { "idTransaction", n => { IdTransaction = n.GetStringValue(); } },
                { "productId", n => { ProductId = n.GetStringValue(); } },
                { "receiptWeight", n => { ReceiptWeight = n.GetDoubleValue(); } },
                { "voyage", n => { Voyage = n.GetStringValue(); } },
                { "weighingPit", n => { WeighingPit = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("DateTimeEnd", DateTimeEnd);
            writer.WriteStringValue("idTransaction", IdTransaction);
            writer.WriteStringValue("productId", ProductId);
            writer.WriteDoubleValue("receiptWeight", ReceiptWeight);
            writer.WriteStringValue("voyage", Voyage);
            writer.WriteDoubleValue("weighingPit", WeighingPit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
