// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SendInspectionLocationAndTimesInput : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Boarding place code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BoardingPlaceCode { get; set; }
#nullable restore
#else
        public string BoardingPlaceCode { get; set; }
#endif
        /// <summary>Cargo type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CargoType { get; set; }
#nullable restore
#else
        public string CargoType { get; set; }
#endif
        /// <summary>Container number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Container { get; set; }
#nullable restore
#else
        public string Container { get; set; }
#endif
        /// <summary>Date and time of inspection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateTimeInspection { get; set; }
#nullable restore
#else
        public string DateTimeInspection { get; set; }
#endif
        /// <summary>Inspection place code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InspectionPlaceCode { get; set; }
#nullable restore
#else
        public string InspectionPlaceCode { get; set; }
#endif
        /// <summary>Remarks</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remarks { get; set; }
#nullable restore
#else
        public string Remarks { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.SendInspectionLocationAndTimesInput"/> and sets the default values.
        /// </summary>
        public SendInspectionLocationAndTimesInput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.SendInspectionLocationAndTimesInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.SendInspectionLocationAndTimesInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.SendInspectionLocationAndTimesInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "boardingPlaceCode", n => { BoardingPlaceCode = n.GetStringValue(); } },
                { "cargoType", n => { CargoType = n.GetStringValue(); } },
                { "container", n => { Container = n.GetStringValue(); } },
                { "dateTimeInspection", n => { DateTimeInspection = n.GetStringValue(); } },
                { "inspectionPlaceCode", n => { InspectionPlaceCode = n.GetStringValue(); } },
                { "remarks", n => { Remarks = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("boardingPlaceCode", BoardingPlaceCode);
            writer.WriteStringValue("cargoType", CargoType);
            writer.WriteStringValue("container", Container);
            writer.WriteStringValue("dateTimeInspection", DateTimeInspection);
            writer.WriteStringValue("inspectionPlaceCode", InspectionPlaceCode);
            writer.WriteStringValue("remarks", Remarks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
