// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    /// <summary>Reschedule flag</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SendStuffingScheduleInput_reschedule
    {
        [EnumMember(Value = "S")]
        #pragma warning disable CS1591
        S,
        #pragma warning restore CS1591
        [EnumMember(Value = "N")]
        #pragma warning disable CS1591
        N,
        #pragma warning restore CS1591
    }
}
