// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    /// <summary>Loaded</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ServiceNumber_loaded
    {
        [EnumMember(Value = "SI")]
        #pragma warning disable CS1591
        SI,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO")]
        #pragma warning disable CS1591
        NO,
        #pragma warning restore CS1591
    }
}
