// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UnidadDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Container status code</summary>
        public double? CodEstadoContenedor { get; set; }
        /// <summary>Hazardous cargo code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodigoCargaPeligrosa { get; set; }
#nullable restore
#else
        public string CodigoCargaPeligrosa { get; set; }
#endif
        /// <summary>Final destination port reported by the shipping line</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FpodReportadoNaviero { get; set; }
#nullable restore
#else
        public string FpodReportadoNaviero { get; set; }
#endif
        /// <summary>Container number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumContenedor { get; set; }
#nullable restore
#else
        public string NumContenedor { get; set; }
#endif
        /// <summary>Origin port reported by the shipping line</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolReportadoNaviero { get; set; }
#nullable restore
#else
        public string PolReportadoNaviero { get; set; }
#endif
        /// <summary>Container seal 1</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sello1 { get; set; }
#nullable restore
#else
        public string Sello1 { get; set; }
#endif
        /// <summary>Container size</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TamanoContenedor { get; set; }
#nullable restore
#else
        public string TamanoContenedor { get; set; }
#endif
        /// <summary>Container type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TipoContenedor { get; set; }
#nullable restore
#else
        public string TipoContenedor { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.UnidadDto"/> and sets the default values.
        /// </summary>
        public UnidadDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.UnidadDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.UnidadDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.UnidadDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "codEstadoContenedor", n => { CodEstadoContenedor = n.GetDoubleValue(); } },
                { "codigoCargaPeligrosa", n => { CodigoCargaPeligrosa = n.GetStringValue(); } },
                { "fpodReportadoNaviero", n => { FpodReportadoNaviero = n.GetStringValue(); } },
                { "numContenedor", n => { NumContenedor = n.GetStringValue(); } },
                { "polReportadoNaviero", n => { PolReportadoNaviero = n.GetStringValue(); } },
                { "sello1", n => { Sello1 = n.GetStringValue(); } },
                { "tamanoContenedor", n => { TamanoContenedor = n.GetStringValue(); } },
                { "tipoContenedor", n => { TipoContenedor = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("codEstadoContenedor", CodEstadoContenedor);
            writer.WriteStringValue("codigoCargaPeligrosa", CodigoCargaPeligrosa);
            writer.WriteStringValue("fpodReportadoNaviero", FpodReportadoNaviero);
            writer.WriteStringValue("numContenedor", NumContenedor);
            writer.WriteStringValue("polReportadoNaviero", PolReportadoNaviero);
            writer.WriteStringValue("sello1", Sello1);
            writer.WriteStringValue("tamanoContenedor", TamanoContenedor);
            writer.WriteStringValue("tipoContenedor", TipoContenedor);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
