// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ValidationResponseScaleIdDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Status code</summary>
        public double? Code { get; set; }
        /// <summary>Date</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>Scale identification</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto_description? Description { get; set; }
#nullable restore
#else
        public global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto_description Description { get; set; }
#endif
        /// <summary>Message</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Stable weight</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StableWeight { get; set; }
#nullable restore
#else
        public string StableWeight { get; set; }
#endif
        /// <summary>Status response</summary>
        public bool? StatusResponse { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto"/> and sets the default values.
        /// </summary>
        public ValidationResponseScaleIdDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetDoubleValue(); } },
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetObjectValue<global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto_description>(global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto_description.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "stableWeight", n => { StableWeight = n.GetStringValue(); } },
                { "statusResponse", n => { StatusResponse = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("code", Code);
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteObjectValue<global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto_description>("description", Description);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("stableWeight", StableWeight);
            writer.WriteBoolValue("statusResponse", StatusResponse);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
