// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    /// <summary>Validation type identifier</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ValidationType
    {
        [EnumMember(Value = "Create")]
        #pragma warning disable CS1591
        Create,
        #pragma warning restore CS1591
        [EnumMember(Value = "Appointment")]
        #pragma warning disable CS1591
        Appointment,
        #pragma warning restore CS1591
        [EnumMember(Value = "Gate In")]
        #pragma warning disable CS1591
        GateIn,
        #pragma warning restore CS1591
    }
}
