// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Italcol.TurboGraneles.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WeighingToSAPResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The responseBody property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Italcol.TurboGraneles.Clients.Models.ResponseBodyDto? ResponseBody { get; set; }
#nullable restore
#else
        public global::Italcol.TurboGraneles.Clients.Models.ResponseBodyDto ResponseBody { get; set; }
#endif
        /// <summary>The responseHeader property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Italcol.TurboGraneles.Clients.Models.ResponseHeaderDto? ResponseHeader { get; set; }
#nullable restore
#else
        public global::Italcol.TurboGraneles.Clients.Models.ResponseHeaderDto ResponseHeader { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Models.WeighingToSAPResponseDto"/> and sets the default values.
        /// </summary>
        public WeighingToSAPResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.WeighingToSAPResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Italcol.TurboGraneles.Clients.Models.WeighingToSAPResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Italcol.TurboGraneles.Clients.Models.WeighingToSAPResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "responseBody", n => { ResponseBody = n.GetObjectValue<global::Italcol.TurboGraneles.Clients.Models.ResponseBodyDto>(global::Italcol.TurboGraneles.Clients.Models.ResponseBodyDto.CreateFromDiscriminatorValue); } },
                { "responseHeader", n => { ResponseHeader = n.GetObjectValue<global::Italcol.TurboGraneles.Clients.Models.ResponseHeaderDto>(global::Italcol.TurboGraneles.Clients.Models.ResponseHeaderDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Italcol.TurboGraneles.Clients.Models.ResponseBodyDto>("responseBody", ResponseBody);
            writer.WriteObjectValue<global::Italcol.TurboGraneles.Clients.Models.ResponseHeaderDto>("responseHeader", ResponseHeader);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
