// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.ProcessAndMove;
using Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.Read;
using Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.Upload;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner
{
    /// <summary>
    /// Builds and executes requests for operations under \scanner\api\v1\scanner
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScannerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The processAndMove property</summary>
        public global::Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.ProcessAndMove.ProcessAndMoveRequestBuilder ProcessAndMove
        {
            get => new global::Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.ProcessAndMove.ProcessAndMoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The read property</summary>
        public global::Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.Read.ReadRequestBuilder Read
        {
            get => new global::Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.Read.ReadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.Upload.UploadRequestBuilder Upload
        {
            get => new global::Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.ScannerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScannerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scanner/api/v1/scanner", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Scanner.Api.V1.Scanner.ScannerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScannerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scanner/api/v1/scanner", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
