// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.Health;
using Italcol.TurboGraneles.Clients.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\scale-weight
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScaleWeightRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The health property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.Health.HealthRequestBuilder Health
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScaleWeightRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/scale-weight?scale={scale}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScaleWeightRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/scale-weight?scale={scale}", rawUrl)
        {
        }
        /// <summary>
        /// Get scale details using the scale identifier
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Italcol.TurboGraneles.Clients.Models.ValidationResponseErrorScaleDto">When receiving a 404 status code</exception>
        /// <exception cref="global::Italcol.TurboGraneles.Clients.Models.ValidationResponseErrorScaleDto">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto?> GetAsync(Action<RequestConfiguration<global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder.ScaleWeightRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto> GetAsync(Action<RequestConfiguration<global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder.ScaleWeightRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Italcol.TurboGraneles.Clients.Models.ValidationResponseErrorScaleDto.CreateFromDiscriminatorValue },
                { "503", global::Italcol.TurboGraneles.Clients.Models.ValidationResponseErrorScaleDto.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto>(requestInfo, global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleIdDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Process scale weight
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Italcol.TurboGraneles.Clients.Models.ValidationResponseErrorScaleDto">When receiving a 404 status code</exception>
        /// <exception cref="global::Italcol.TurboGraneles.Clients.Models.ValidationResponseErrorScaleDto">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleDto?> PostAsync(global::Italcol.TurboGraneles.Clients.Models.ValidationRequestScaleDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleDto> PostAsync(global::Italcol.TurboGraneles.Clients.Models.ValidationRequestScaleDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Italcol.TurboGraneles.Clients.Models.ValidationResponseErrorScaleDto.CreateFromDiscriminatorValue },
                { "503", global::Italcol.TurboGraneles.Clients.Models.ValidationResponseErrorScaleDto.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleDto>(requestInfo, global::Italcol.TurboGraneles.Clients.Models.ValidationResponseScaleDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get scale details using the scale identifier
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder.ScaleWeightRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder.ScaleWeightRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Process scale weight
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Italcol.TurboGraneles.Clients.Models.ValidationRequestScaleDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Italcol.TurboGraneles.Clients.Models.ValidationRequestScaleDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/api/v1/scale-weight", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get scale details using the scale identifier
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ScaleWeightRequestBuilderGetQueryParameters 
        {
            /// <summary>Scale identifier: b-1</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("scale")]
            public string? Scale { get; set; }
#nullable restore
#else
            [QueryParameter("scale")]
            public string Scale { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ScaleWeightRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Italcol.TurboGraneles.Clients.Api.V1.ScaleWeight.ScaleWeightRequestBuilder.ScaleWeightRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ScaleWeightRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
