// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Api.V1.Dian.ConsultManifest;
using Italcol.TurboGraneles.Clients.Api.V1.Dian.EntryNotice;
using Italcol.TurboGraneles.Clients.Api.V1.Dian.FinalizeVessel;
using Italcol.TurboGraneles.Clients.Api.V1.Dian.Health;
using Italcol.TurboGraneles.Clients.Api.V1.Dian.ImportDeclaration;
using Italcol.TurboGraneles.Clients.Api.V1.Dian.Jobs;
using Italcol.TurboGraneles.Clients.Api.V1.Dian.ReportTarja;
using Italcol.TurboGraneles.Clients.Api.V1.Dian.SendArim;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Api.V1.Dian
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\dian
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DianRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The consultManifest property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Dian.ConsultManifest.ConsultManifestRequestBuilder ConsultManifest
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Dian.ConsultManifest.ConsultManifestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The entryNotice property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Dian.EntryNotice.EntryNoticeRequestBuilder EntryNotice
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Dian.EntryNotice.EntryNoticeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The finalizeVessel property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Dian.FinalizeVessel.FinalizeVesselRequestBuilder FinalizeVessel
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Dian.FinalizeVessel.FinalizeVesselRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Dian.Health.HealthRequestBuilder Health
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Dian.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The importDeclaration property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Dian.ImportDeclaration.ImportDeclarationRequestBuilder ImportDeclaration
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Dian.ImportDeclaration.ImportDeclarationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Dian.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Dian.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reportTarja property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Dian.ReportTarja.ReportTarjaRequestBuilder ReportTarja
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Dian.ReportTarja.ReportTarjaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendArim property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Dian.SendArim.SendArimRequestBuilder SendArim
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Dian.SendArim.SendArimRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Dian.DianRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DianRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dian", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Dian.DianRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DianRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dian", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
