// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ConvertJsonToXml;
using Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ErpAutenticate;
using Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ErpCreateInvoice;
using Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ErpCreatePayment;
using Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.Health;
using Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.LoginRequest;
using Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.SendElectronicInvoice;
using Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.SendInvoice;
using Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.TosToIfs;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\electronic-invoice
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ElectronicInvoiceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The convertJsonToXml property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ConvertJsonToXml.ConvertJsonToXmlRequestBuilder ConvertJsonToXml
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ConvertJsonToXml.ConvertJsonToXmlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The erpAutenticate property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ErpAutenticate.ErpAutenticateRequestBuilder ErpAutenticate
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ErpAutenticate.ErpAutenticateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The erpCreateInvoice property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ErpCreateInvoice.ErpCreateInvoiceRequestBuilder ErpCreateInvoice
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ErpCreateInvoice.ErpCreateInvoiceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The erpCreatePayment property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ErpCreatePayment.ErpCreatePaymentRequestBuilder ErpCreatePayment
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ErpCreatePayment.ErpCreatePaymentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.Health.HealthRequestBuilder Health
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The loginRequest property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.LoginRequest.LoginRequestRequestBuilder LoginRequest
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.LoginRequest.LoginRequestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendElectronicInvoice property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.SendElectronicInvoice.SendElectronicInvoiceRequestBuilder SendElectronicInvoice
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.SendElectronicInvoice.SendElectronicInvoiceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendInvoice property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.SendInvoice.SendInvoiceRequestBuilder SendInvoice
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.SendInvoice.SendInvoiceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tosToIfs property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.TosToIfs.TosToIfsRequestBuilder TosToIfs
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.TosToIfs.TosToIfsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ElectronicInvoiceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ElectronicInvoiceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/electronic-invoice", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.ElectronicInvoice.ElectronicInvoiceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ElectronicInvoiceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/electronic-invoice", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
