// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Oauth2.Health;
using Italcol.TurboGraneles.Clients.Oauth2.Token;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Oauth2
{
    /// <summary>
    /// Builds and executes requests for operations under \oauth2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Oauth2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The health property</summary>
        public global::Italcol.TurboGraneles.Clients.Oauth2.Health.HealthRequestBuilder Health
        {
            get => new global::Italcol.TurboGraneles.Clients.Oauth2.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::Italcol.TurboGraneles.Clients.Oauth2.Token.TokenRequestBuilder Token
        {
            get => new global::Italcol.TurboGraneles.Clients.Oauth2.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Oauth2.Oauth2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Oauth2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Oauth2.Oauth2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Oauth2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
