// <auto-generated/>
#pragma warning disable CS0618
using Italcol.TurboGraneles.Clients.Api.V1.Mintransporte.AppointmentValidation;
using Italcol.TurboGraneles.Clients.Api.V1.Mintransporte.Health;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Italcol.TurboGraneles.Clients.Api.V1.Mintransporte
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\mintransporte
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MintransporteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The appointmentValidation property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Mintransporte.AppointmentValidation.AppointmentValidationRequestBuilder AppointmentValidation
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Mintransporte.AppointmentValidation.AppointmentValidationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::Italcol.TurboGraneles.Clients.Api.V1.Mintransporte.Health.HealthRequestBuilder Health
        {
            get => new global::Italcol.TurboGraneles.Clients.Api.V1.Mintransporte.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Mintransporte.MintransporteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MintransporteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/mintransporte", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Italcol.TurboGraneles.Clients.Api.V1.Mintransporte.MintransporteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MintransporteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/mintransporte", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
